
spring:
#  config:
#    activate:
#      on-profile: local
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
  devtools:
    livereload:
      enabled: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/survey;
    driver-class-name: org.h2.Driver
    username: aladdin
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true

jwt:
  access-token:
    secret: +iBcUJRWGvl+94+ow4nXV1fzWIq4rph8x7MyRmrtWio=
    expiration: 60000
  refresh-token:
    secret: gtzRlqF6bIkmOi5i15A9G5xbLdwiAMmZi6JPOeemC1E=
    expiration: 86400000

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    org: INFO
    com: DEBUG
    root: INFO