### 사용자 전체 정보
@access-token = client.global.get("access-token")
@api-key = client.global.get("api-key")

### 설문조사 전체 정보
GET {{domain}}:{{port}}/surveys
Authorization: Bearer {{access-token}}

### 설문조사 정보 (설문조사 ID)
GET {{domain}}:{{port}}/surveys/1
Authorization: Bearer {{access-token}}

### 내 설문조사 정보
GET {{domain}}:{{port}}/surveys/find-own
Authorization: Bearer {{access-token}}

### 설문조사 입력
POST {{domain}}:{{port}}/surveys
Content-Type: application/json
Authorization: Bearer {{access-token}}

{
  "title": "설문조사 테스트",
  "description": "설문조사 설명",
  "center": {
    "x": 126.978388,
    "y": 37.566610
  },
  "content": "{\"sections\":[{\"section_name\":\"General Knowledge\",\"next_section\":\"Science\",\"questions\":[{\"question_text\":\"What is the capital of France?\",\"answers\":[\"Paris\",\"London\",\"Berlin\"]},{\"question_text\":\"Who wrote Romeo and Juliet?\",\"answers\":[\"William Shakespeare\",\"Jane Austen\",\"Charles Dickens\"]}]},{\"section_name\":\"Science\",\"questions\":[{\"question_text\":\"What is the largest mammal on Earth?\",\"answers\":[\"Blue Whale\",\"Elephant\",\"Giraffe\"]}]}]}"
}

### 설문조사 수정
PATCH {{domain}}:{{port}}/surveys/1
Content-Type: application/json
Authorization: Bearer {{access-token}}

{
  "title": "설문 조사 수정 테스트",
  "description": "설문 조사 설명 수정",
  "center": {
    "x": 125.978388,
    "y": 37.566610
  },
  "content": "{\"sections\":[{\"section_name\":\"General Knowledge\",\"next_section\":\"Science\",\"questions\":[{\"question_text\":\"What is the capital of France?\",\"answers\":[\"Paris\",\"London\",\"Berlin\"]},{\"question_text\":\"Who wrote Romeo and Juliet?\",\"answers\":[\"William Shakespeare\",\"Jane Austen\",\"Charles Dickens\"]}]},{\"section_name\":\"Science\",\"questions\":[{\"question_text\":\"What is the largest mammal on Earth?\",\"answers\":[\"Blue Whale\",\"Elephant\",\"Giraffe\"]}]}]}"
}


### 설문조사 발행
PATCH {{domain}}:{{port}}/surveys/1/publish
Content-Type: application/json
Authorization: Bearer {{access-token}}

### 설문조사 삭제
DELETE {{domain}}:{{port}}/surveys/
Content-Type: application/json
Authorization: Bearer {{access-token}}

### 설문조사  OPEN API
GET {{domain}}:{{port}}/open-api/survey/ba68cd2c-ce90-4174-9691-b746c24cfae0
API-KEY: 39e3f5ca-2f92-492d-b95e-fa185c204203
